sudo : required
language: generic 
services :
    - docker

before_install:
    - docker build -t khandelwalsumit/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true khandelwalsumit/docker-react npm run test